<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CamposFormularioSeeder extends Seeder
{
    public function run(): void
    {
        // Busca o ciclo criado no seeder anterior para amarrar os relacionamentos dinamicamente
        $cicloId = DB::table('ciclos')->where('ano', 2026)->where('semestre', 2)->value('id');

        if (!$cicloId) {
            $this->command->warn('Ciclo do 2º Semestre de 2026 não encontrado. Rode o Ciclo2026Seeder primeiro.');
            return;
        }

        $campos = [
            [
                'etapa' => 2,
                'label' => 'Gênero',
                'name' => 'genero',
                'tipo' => 'radio',
                'opcoes' => '["Mulher Cis","Mulher Trans","Pessoa não-binária","Homem Cis","Homem Trans","Prefiro não informar","Outro"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 2,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"layout_opcoes":"vertical"}',
            ],
            [
                'etapa' => 0,
                'label' => 'Configurações Globais',
                'name' => '_form_config',
                'tipo' => 'config',
                'opcoes' => null,
                'obrigatorio' => false,
                'regras_validacao' => null,
                'ordem' => 0,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"bg_image":"storage/formularios/bg/Mc8ZVUceOSpDQH0Epdtax26m7KXuamVqI9foc5bu.png","bg_color":"#ffffff","bg_opacity":"0.0","bg_size":"cover","form_width":"max-w-2xl","translucent_card":true,"use_vacancy_limit":true}',
            ],
            [
                'etapa' => 1,
                'label' => 'Teste',
                'name' => 'teste',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => false,
                'regras_validacao' => '',
                'ordem' => 1,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Qual serviço de assistência social e/ou saúde indicou você para o Percorre',
                'name' => 'qual_servico_de_assistencia_social_eou_saude_indicou_voce_para_o_percorre',
                'tipo' => 'select',
                'opcoes' => '["CA / CTA / CAE - Centro de Acolhida / Centro de Acolhida Especial","CAPS (Centro de Atenção Psicossocial), ou CERSAMi (Centro de Referência em Saúde Mental Infanto-Juvenil)","CCA","CCInter - Centros de Convivência Intergeracional","CDHU(Companhia de Desenvolvimento Habitacional e Urbano)","CECCO - Centros de Convivência e Cooperativa","CEDESP - Centros de Desenvolvimento Social e Produtivo para Adolescentes, Jovens e Adultos","Centro de atendimentos às vítimas de violência à mulher","Centro de Referência LGBTI+","CEPAT (Centro Público de Atendimento ao Trabalhador)","CERCCA (Centro de Referência para o cuidado a criança e adolescentes e suas famílias em situação de violência)","CEU - Centros Educacionais Unificados","Circo Social","CJ (Centro para Juventude-SP)","CONSELHO TUTELAR","CRAI - Centro de Referência e Atendimento para Imigrantes","CRAS (Centro de Referência de Assistência Social)","CREAS (Centro de Referência Especializado de Assistência Social)","Fábricas de Cultura","INSS","NPJ (Núcleo de Práticas Juridicas)","NAISPD - Núcleo de Apoio à Inclusão Social para Pessoas com Deficiência","ONGs diversas","República Jovem","SAICA (Serviço de Acolhimento Institucional para Crianças e Adolescentes)","SASF (Serviço de Assistência Social à Família)","SMSE (Serviço de Medida Sócio Educativa)","SPVV (Serviço de Proteção Social à Criança e Adolescente Vítima de Violência)","UBS (Unidade Básica de Saúde) Posto de Saúde e Clínica da Família","Outro"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 15,
                'depende_de' => 'voce_foi_indicado_por_algum_servico_de_assistencia_social_eou_saude',
                'depende_valor' => 'Sim',
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Qual o nome do serviço?',
                'name' => 'qual_o_nome_do_servico',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 16,
                'depende_de' => 'qual_servico_de_assistencia_social_eou_saude_indicou_voce_para_o_percorre',
                'depende_valor' => 'Outro',
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 3,
                'label' => 'Nome da mãe',
                'name' => 'nome_da_mae',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 1,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Cor / Raça',
                'name' => 'cor_raca',
                'tipo' => 'radio',
                'opcoes' => '["Branca","Parda","Preta","Amarela","Indígena"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 3,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"layout_opcoes":"vertical"}',
            ],
            [
                'etapa' => 3,
                'label' => 'Nome do responsável',
                'name' => 'nome_do_responsavel',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 2,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 3,
                'label' => 'Informe o contato de um responsável',
                'name' => 'informe_o_contato_de_um_responsavel',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 3,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'tel',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Gênero (Outro)',
                'name' => 'genero_outro',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 4,
                'depende_de' => 'genero',
                'depende_valor' => 'Outro',
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Renda Familiar',
                'name' => 'renda_familiar',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 11,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'money',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 3,
                'label' => 'Como conheceu o Percorre?',
                'name' => 'como_conheceu_o_percorre',
                'tipo' => 'select',
                'opcoes' => '["Redes Sociais","Google","Escola","Etec","Professor(a) do Instituto","Indicação de Aluno","Indicação de Ex-aluno","Empresa Parceira do Instituto","Televisão","Outros"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 4,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Grau de escolaridade',
                'name' => 'grau_de_escolaridade',
                'tipo' => 'select',
                'opcoes' => '["Fundamental","Médio","Superior","Técnico"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 5,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Qual ano',
                'name' => 'qual_ano',
                'tipo' => 'select',
                'opcoes' => '["1 Ano","2 Ano","3 Ano"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 6,
                'depende_de' => 'grau_de_escolaridade',
                'depende_valor' => 'Médio',
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Série',
                'name' => 'serie',
                'tipo' => 'select',
                'opcoes' => '["7 Série","8 Série","9 Série"]',
                'obrigatorio' => false,
                'regras_validacao' => '',
                'ordem' => 7,
                'depende_de' => 'grau_de_escolaridade',
                'depende_valor' => 'Fundamental',
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Qual o sexo atribuído a você no seu nascimento?',
                'name' => 'qual_o_sexo_atribuido_a_voce_no_seu_nascimento',
                'tipo' => 'radio',
                'opcoes' => '["Homem","Mulher","Intersexo","Prefiro não informar"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 1,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"layout_opcoes":"vertical"}',
            ],
            [
                'etapa' => 3,
                'label' => 'Você é ex-aluno(a)?',
                'name' => 'voce_e_ex_alunoa',
                'tipo' => 'select',
                'opcoes' => '["Sim","Não"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 5,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 3,
                'label' => 'Marque o nome do curso que você fez:',
                'name' => 'marque_o_nome_do_curso_que_voce_fez',
                'tipo' => 'radio',
                'opcoes' => '["Gestão Empresarial com Software ERP","Microsoft Office com Zendesk","Power BI","Programação Web","Suporte em TI","Outro"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 6,
                'depende_de' => 'voce_e_ex_alunoa',
                'depende_valor' => 'Sim',
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"layout_opcoes":"vertical"}',
            ],
            [
                'etapa' => 3,
                'label' => 'Nome do curso',
                'name' => 'nome_do_curso',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 7,
                'depende_de' => 'marque_o_nome_do_curso_que_voce_fez',
                'depende_valor' => 'Outro',
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 3,
                'label' => 'Suas redes sociais',
                'name' => 'campo_1787860858',
                'tipo' => 'social',
                'opcoes' => null,
                'obrigatorio' => false,
                'regras_validacao' => '',
                'ordem' => 8,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"redes_permitidas":["instagram","tiktok"]}',
            ],
            [
                'etapa' => 3,
                'label' => 'Você já trabalhou?',
                'name' => 'voce_ja_trabalhou',
                'tipo' => 'radio',
                'opcoes' => '["Sim","Não"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 9,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"layout_opcoes":"vertical"}',
            ],
            [
                'etapa' => 2,
                'label' => 'Andamento do curso',
                'name' => 'andamento_do_curso',
                'tipo' => 'select',
                'opcoes' => '["Concluído","Cursando","Interrompido / Abandono do ensino sem a conclusão do mesmo"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 8,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Nome da escola ou instituição de ensino',
                'name' => 'nome_da_escola_ou_instituicao_de_ensino',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 9,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Instituição',
                'name' => 'instituicao',
                'tipo' => 'select',
                'opcoes' => '["Pública","Privada"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 10,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Bolsista?',
                'name' => 'bolsista',
                'tipo' => 'select',
                'opcoes' => '["Sim","Não"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 12,
                'depende_de' => 'instituicao',
                'depende_valor' => 'Privada',
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Quantidade de pessoas que moram na casa, incluindo você',
                'name' => 'quantidade_de_pessoas_que_moram_na_casa_incluindo_voce',
                'tipo' => 'text',
                'opcoes' => null,
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 13,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'number',
                'depende_operador' => '=',
                'configuracoes' => null,
            ],
            [
                'etapa' => 2,
                'label' => 'Você foi indicado por algum serviço de assistência social e/ou saúde?',
                'name' => 'voce_foi_indicado_por_algum_servico_de_assistencia_social_eou_saude',
                'tipo' => 'radio',
                'opcoes' => '["Sim","Não"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 14,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 12,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"layout_opcoes":"vertical"}',
            ],
            [
                'etapa' => 3,
                'label' => 'Formato de trabalho:',
                'name' => 'formato_de_trabalho',
                'tipo' => 'radio',
                'opcoes' => '["Formal","Informal"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 10,
                'depende_de' => 'voce_ja_trabalhou',
                'depende_valor' => 'Sim',
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => '{"layout_opcoes":"vertical"}',
            ],
            [
                'etapa' => 3,
                'label' => 'Quanto tempo de deslocamento você leva da sua casa até a unidade escolhida?',
                'name' => 'quanto_tempo_de_deslocamento_voce_leva_da_sua_casa_ate_a_unidade_escolhida',
                'tipo' => 'select',
                'opcoes' => '["Até 30 minutos","Entre 30 minutos e 1 hora","Entre 1 hora e 1 hora e 30 minutos","Acima de 1 hora e 30 minutos"]',
                'obrigatorio' => true,
                'regras_validacao' => '',
                'ordem' => 11,
                'depende_de' => null,
                'depende_valor' => null,
                'largura' => 6,
                'subtipo' => 'text',
                'depende_operador' => '=',
                'configuracoes' => null,
            ]
        ];

        foreach ($campos as $campo) {
            // Associa o campo dinamicamente com o ciclo (substituindo ID hardcoded)
            $campo['ciclo_id'] = $cicloId; 
            
            DB::table('campos_formularios')->insertOrIgnore(array_merge($campo, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}