<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Modules\Unidade\Domain\Models\Unidade;

class UnidadesTesteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $unidades = [
            [
                'nome' => 'SP - Santana',
                'slug' => 'sede_santana_sp',
                'status' => 'Ativa',
                'data_inauguracao' => '2018-03-12',
                'endereco' => 'Av. Cruzeiro do Sul, 2840',
                'cep' => '02030-000',
                'estado' => 'SP',
                'cidade' => 'São Paulo',
                'bairro' => 'Santana',
                'logradouro' => 'Av. Cruzeiro do Sul',
                'numero' => '2840',
                'complemento' => '2º andar',
                'email' => 'santana@instituicao.org.br',
                'telefone' => '(11) 2234-5600',
                'foto_path' => null,
            ],

            [
                'nome' => 'SP - Jardim Ângela',
                'slug' => 'jardim_angela_sp',
                'status' => 'Ativa',
                'data_inauguracao' => '2019-08-20',
                'endereco' => 'Estrada do M’Boi Mirim, 4850',
                'cep' => '04905-000',
                'estado' => 'SP',
                'cidade' => 'São Paulo',
                'bairro' => 'Jardim Ângela',
                'logradouro' => 'Estrada do M’Boi Mirim',
                'numero' => '4850',
                'complemento' => null,
                'email' => 'jardim.angela@instituicao.org.br',
                'telefone' => '(11) 5834-2100',
                'foto_path' => null,
            ],

            [
                'nome' => 'MG - Barreiro',
                'slug' => 'barreiro_bh_mg',
                'status' => 'Ativa',
                'data_inauguracao' => '2017-05-15',
                'endereco' => 'Av. Sinfrônio Brochado, 1250',
                'cep' => '30640-000',
                'estado' => 'MG',
                'cidade' => 'Belo Horizonte',
                'bairro' => 'Barreiro',
                'logradouro' => 'Av. Sinfrônio Brochado',
                'numero' => '1250',
                'complemento' => 'Sala 12',
                'email' => 'barreiro@instituicao.org.br',
                'telefone' => '(31) 3321-4500',
                'foto_path' => null,
            ],

            [
                'nome' => 'PE - Recife',
                'slug' => 'boa_vista_recife_pe',
                'status' => 'Ativa',
                'data_inauguracao' => '2016-09-10',
                'endereco' => 'Rua do Hospício, 420',
                'cep' => '50060-080',
                'estado' => 'PE',
                'cidade' => 'Recife',
                'bairro' => 'Boa Vista',
                'logradouro' => 'Rua do Hospício',
                'numero' => '420',
                'complemento' => '1º andar',
                'email' => 'recife@instituicao.org.br',
                'telefone' => '(81) 3221-7800',
                'foto_path' => null,
            ],

            [
                'nome' => 'SP - Hortolândia',
                'slug' => 'jardim_boa_esperanca_hortolandia_sp',
                'status' => 'Ativa',
                'data_inauguracao' => '2020-02-17',
                'endereco' => 'Rua das Palmeiras, 780',
                'cep' => '13183-000',
                'estado' => 'SP',
                'cidade' => 'Hortolândia',
                'bairro' => 'Jardim Boa Esperança',
                'logradouro' => 'Rua das Palmeiras',
                'numero' => '780',
                'complemento' => null,
                'email' => 'hortolandia@instituicao.org.br',
                'telefone' => '(19) 3865-3200',
                'foto_path' => null,
            ],

            [
                'nome' => 'SP - Itaquera',
                'slug' => 'itaquera_sp',
                'status' => 'Ativa',
                'data_inauguracao' => '2018-11-05',
                'endereco' => 'Rua Victório Santim, 980',
                'cep' => '08290-000',
                'estado' => 'SP',
                'cidade' => 'São Paulo',
                'bairro' => 'Itaquera',
                'logradouro' => 'Rua Victório Santim',
                'numero' => '980',
                'complemento' => null,
                'email' => 'itaquera@instituicao.org.br',
                'telefone' => '(11) 2524-6800',
                'foto_path' => null,
            ],

            [
                'nome' => 'SP - Jardim Santa Regina',
                'slug' => 'jardim_santa_regina_sp',
                'status' => 'Ativa',
                'data_inauguracao' => '2021-04-12',
                'endereco' => 'Rua Santa Regina, 315',
                'cep' => '04858-000',
                'estado' => 'SP',
                'cidade' => 'São Paulo',
                'bairro' => 'Jardim Santa Regina',
                'logradouro' => 'Rua Santa Regina',
                'numero' => '315',
                'complemento' => null,
                'email' => 'santa.regina@instituicao.org.br',
                'telefone' => '(11) 5524-1900',
                'foto_path' => null,
            ],

            [
                'nome' => 'RS - Porto Alegre',
                'slug' => 'cidade_baixa_poa_rs',
                'status' => 'Ativa',
                'data_inauguracao' => '2017-10-23',
                'endereco' => 'Rua Lima e Silva, 640',
                'cep' => '90050-100',
                'estado' => 'RS',
                'cidade' => 'Porto Alegre',
                'bairro' => 'Cidade Baixa',
                'logradouro' => 'Rua Lima e Silva',
                'numero' => '640',
                'complemento' => '3º andar',
                'email' => 'porto.alegre@instituicao.org.br',
                'telefone' => '(51) 3224-5100',
                'foto_path' => null,
            ],

            [
                'nome' => 'MG - São Gabriel',
                'slug' => 'sao_gabriel_bh_mg',
                'status' => 'Ativa',
                'data_inauguracao' => '2019-03-18',
                'endereco' => 'Av. Cristiano Machado, 7200',
                'cep' => '31910-810',
                'estado' => 'MG',
                'cidade' => 'Belo Horizonte',
                'bairro' => 'São Gabriel',
                'logradouro' => 'Av. Cristiano Machado',
                'numero' => '7200',
                'complemento' => 'Bloco B',
                'email' => 'sao.gabriel@instituicao.org.br',
                'telefone' => '(31) 3434-2700',
                'foto_path' => null,
            ],

            [
                'nome' => 'SP - Vila Nova',
                'slug' => 'vila_nova_santos_sp',
                'status' => 'Ativa',
                'data_inauguracao' => '2020-08-03',
                'endereco' => 'Rua Carvalho de Mendonça, 520',
                'cep' => '11070-100',
                'estado' => 'SP',
                'cidade' => 'Santos',
                'bairro' => 'Vila Nova',
                'logradouro' => 'Rua Carvalho de Mendonça',
                'numero' => '520',
                'complemento' => null,
                'email' => 'santos@instituicao.org.br',
                'telefone' => '(13) 3234-7200',
                'foto_path' => null,
            ],

            [
                'nome' => 'SP - Cidade Ariston',
                'slug' => 'cidade_ariston_carapicuiba_sp',
                'status' => 'Ativa',
                'data_inauguracao' => '2021-06-21',
                'endereco' => 'Av. Marginal do Ribeirão, 1150',
                'cep' => '06390-000',
                'estado' => 'SP',
                'cidade' => 'Carapicuíba',
                'bairro' => 'Cidade Ariston',
                'logradouro' => 'Av. Marginal do Ribeirão',
                'numero' => '1150',
                'complemento' => null,
                'email' => 'carapicuiba@instituicao.org.br',
                'telefone' => '(11) 4184-6300',
                'foto_path' => null,
            ],

            [
                'nome' => 'RJ - Engenho Novo',
                'slug' => 'engenho_novo_rj',
                'status' => 'Ativa',
                'data_inauguracao' => '2018-07-16',
                'endereco' => 'Rua Barão do Bom Retiro, 1450',
                'cep' => '20715-003',
                'estado' => 'RJ',
                'cidade' => 'Rio de Janeiro',
                'bairro' => 'Engenho Novo',
                'logradouro' => 'Rua Barão do Bom Retiro',
                'numero' => '1450',
                'complemento' => 'Sala 5',
                'email' => 'engenho.novo@instituicao.org.br',
                'telefone' => '(21) 2269-4100',
                'foto_path' => null,
            ],

            [
                'nome' => 'SP - São José do Rio Preto',
                'slug' => 'sao_jose_rio_preto_sp',
                'status' => 'Ativa',
                'data_inauguracao' => '2019-11-11',
                'endereco' => 'Av. Alberto Andaló, 2850',
                'cep' => '15015-000',
                'estado' => 'SP',
                'cidade' => 'São José do Rio Preto',
                'bairro' => 'Centro',
                'logradouro' => 'Av. Alberto Andaló',
                'numero' => '2850',
                'complemento' => null,
                'email' => 'riopreto@instituicao.org.br',
                'telefone' => '(17) 3234-8500',
                'foto_path' => null,
            ],
        ];

        foreach ($unidades as $unidade) {
            Unidade::updateOrCreate(
                ['slug' => $unidade['slug']],
                $unidade
            );
        }
    }
}
